- name: init master
  hosts: master
  tasks:
  - name: kubeadm init master
    ansible.builtin.shell: 'kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt'
    become: true
    become_user: root

  - name: copy admin.conf to users kube config
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes

  - name: kubectl apply flannel
    ansible.builtin.shell: 'kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt'
    become: true
    become_user: root
